development:
  adapter: postgresql
  database: spindi_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: spindi_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: spindi_production
  pool: 5
  timeout: 5000
