# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
# Word.create(spindi: 'макло', bg: 'малко')
# Word.create(spindi: 'ас', bg: 'аз')
# Word.create(spindi: 'фостата', bg: 'в устата')
# Word.create(spindi: 'биах', bg: 'бях')
# Word.create(spindi: 'ф', bg: 'в')
# Word.create(spindi: 'луксозенец', bg: 'лозенец')

Word.create(spindi: "маимонки", bg: "маймунки") unless Word.exists?(spindi: "маимонки")
Word.create(spindi: "маимонка", bg: "маймунка") unless Word.exists?(spindi: "маимонка")
Word.create(spindi: "маимонке", bg: "маймунке") unless Word.exists?(spindi: "маимонке")
Word.create(spindi: "мои", bg: "мой") unless Word.exists?(spindi: "мои")
Word.create(spindi: "колем", bg: "колим") unless Word.exists?(spindi: "колем")
Word.create(spindi: "пумагам", bg: "помагам") unless Word.exists?(spindi: "пумагам")
Word.create(spindi: "заги", bg: "зиг") unless Word.exists?(spindi: "заги")
Word.create(spindi: "халил", bg: "хайл") unless Word.exists?(spindi: "халил")
Word.create(spindi: "емам", bg: "имам") unless Word.exists?(spindi: "емам")
Word.create(spindi: "петмо", bg: "петно") unless Word.exists?(spindi: "петмо")
Word.create(spindi: "молиа", bg: "моля") unless Word.exists?(spindi: "молиа")
Word.create(spindi: "та", bg: "те") unless Word.exists?(spindi: "та")
Word.create(spindi: "исчисти", bg: "изчисти") unless Word.exists?(spindi: "исчисти")
Word.create(spindi: "йа", bg: "я") unless Word.exists?(spindi: "йа")
Word.create(spindi: "дубре", bg: "добре") unless Word.exists?(spindi: "дубре")
Word.create(spindi: "домеса", bg: "донеса") unless Word.exists?(spindi: "домеса")
Word.create(spindi: "препарад", bg: "препарат") unless Word.exists?(spindi: "препарад")
Word.create(spindi: "3ф1", bg: "3в1") unless Word.exists?(spindi: "3ф1")
Word.create(spindi: "бражо", bg: "браво") unless Word.exists?(spindi: "бражо")
Word.create(spindi: "готожо", bg: "готово") unless Word.exists?(spindi: "готожо")
Word.create(spindi: "чисту", bg: "чисто") unless Word.exists?(spindi: "чисту")
Word.create(spindi: "меку", bg: "меко") unless Word.exists?(spindi: "меку")
Word.create(spindi: "биало", bg: "бяло") unless Word.exists?(spindi: "биало")
Word.create(spindi: "пипаите", bg: "пипайте") unless Word.exists?(spindi: "пипаите")
Word.create(spindi: "задошажам", bg: "задушавам") unless Word.exists?(spindi: "задошажам")
Word.create(spindi: "енн", bg: "нее") unless Word.exists?(spindi: "енн")
Word.create(spindi: "ис", bg: "си") unless Word.exists?(spindi: "ис")
Word.create(spindi: "монстар", bg: "монстър") unless Word.exists?(spindi: "монстар")
Word.create(spindi: "кремжирш", bg: "кренвирш") unless Word.exists?(spindi: "кремжирш")
Word.create(spindi: "уко", bg: "око") unless Word.exists?(spindi: "уко")
Word.create(spindi: "заб", bg: "зъб") unless Word.exists?(spindi: "заб")
Word.create(spindi: "краг", bg: "крак") unless Word.exists?(spindi: "краг")
Word.create(spindi: "мужи", bg: "може") unless Word.exists?(spindi: "мужи")
Word.create(spindi: "гожори", bg: "говори") unless Word.exists?(spindi: "гожори")
Word.create(spindi: "саета", bg: "заета") unless Word.exists?(spindi: "саета")
Word.create(spindi: "сает", bg: "зает") unless Word.exists?(spindi: "сает")
Word.create(spindi: "лао", bg: "ало") unless Word.exists?(spindi: "лао")
Word.create(spindi: "какжо", bg: "какво") unless Word.exists?(spindi: "какжо")
Word.create(spindi: "стажа", bg: "става") unless Word.exists?(spindi: "стажа")
Word.create(spindi: "скапа", bg: "скъпа") unless Word.exists?(spindi: "скапа")
Word.create(spindi: "романтиг", bg: "романтик") unless Word.exists?(spindi: "романтиг")
Word.create(spindi: "полодиаххххх", bg: "полудяххххх") unless Word.exists?(spindi: "полодиаххххх")
Word.create(spindi: "кренжрши", bg: "кренвирши") unless Word.exists?(spindi: "кренжрши")
Word.create(spindi: "оста", bg: "уста") unless Word.exists?(spindi: "оста")
Word.create(spindi: "остата", bg: "устата") unless Word.exists?(spindi: "остата")
Word.create(spindi: "разист", bg: "расист") unless Word.exists?(spindi: "разист")
Word.create(spindi: "амти", bg: "анти") unless Word.exists?(spindi: "амти")
Word.create(spindi: "пайджина", bg: "паяжина") unless Word.exists?(spindi: "пайджина")
Word.create(spindi: "фиргам", bg: "хвърлям") unless Word.exists?(spindi: "фиргам")
Word.create(spindi: "им", bg: "ми") unless Word.exists?(spindi: "им")
Word.create(spindi: "тои", bg: "той") unless Word.exists?(spindi: "тои")
Word.create(spindi: "омриал", bg: "умрял") unless Word.exists?(spindi: "омриал")
Word.create(spindi: "шанпионкса", bg: "шампионска") unless Word.exists?(spindi: "шанпионкса")
Word.create(spindi: "илга", bg: "лига") unless Word.exists?(spindi: "илга")
Word.create(spindi: "шанпионкси", bg: "шампионски") unless Word.exists?(spindi: "шанпионкси")
Word.create(spindi: "пражиа", bg: "правя") unless Word.exists?(spindi: "пражиа")
Word.create(spindi: "брасилиа", bg: "бразилия", name: true) unless Word.exists?(spindi: "брасилиа")
Word.create(spindi: "гемраниа", bg: "германия", name: true) unless Word.exists?(spindi: "гемраниа")
Word.create(spindi: "тагтика", bg: "тактика") unless Word.exists?(spindi: "тагтика")
Word.create(spindi: "аппата", bg: "папата", name: true) unless Word.exists?(spindi: "аппата")
Word.create(spindi: "аппа", bg: "папа") unless Word.exists?(spindi: "аппа")
Word.create(spindi: "нйе", bg: "ние") unless Word.exists?(spindi: "нйе")
Word.create(spindi: "наи", bg: "най") unless Word.exists?(spindi: "наи")
Word.create(spindi: "ножата", bg: "новата") unless Word.exists?(spindi: "ножата")
Word.create(spindi: "ножа", bg: "нова") unless Word.exists?(spindi: "ножа")
Word.create(spindi: "омри", bg: "умри") unless Word.exists?(spindi: "омри")
Word.create(spindi: "жажно", bg: "важно") unless Word.exists?(spindi: "жажно")
Word.create(spindi: "саобштение", bg: "съобщение") unless Word.exists?(spindi: "саобштение")
Word.create(spindi: "страмицата", bg: "страницата") unless Word.exists?(spindi: "страмицата")
Word.create(spindi: "отножо", bg: "отново") unless Word.exists?(spindi: "отножо")
Word.create(spindi: "истрита", bg: "изтрита") unless Word.exists?(spindi: "истрита")
Word.create(spindi: "расбери", bg: "разбери") unless Word.exists?(spindi: "расбери")
Word.create(spindi: "тап", bg: "тъп") unless Word.exists?(spindi: "тап")
Word.create(spindi: "ем", bg: "ме") unless Word.exists?(spindi: "ем")
Word.create(spindi: "отре", bg: "утре") unless Word.exists?(spindi: "отре")
Word.create(spindi: "посна", bg: "постна") unless Word.exists?(spindi: "посна")
Word.create(spindi: "прес", bg: "през") unless Word.exists?(spindi: "прес")
Word.create(spindi: "бадка", bg: "батка") unless Word.exists?(spindi: "бадка")
Word.create(spindi: "жлизай", bg: "влизай") unless Word.exists?(spindi: "жлизай")
Word.create(spindi: "блогирана", bg: "блокирана") unless Word.exists?(spindi: "блогирана")
Word.create(spindi: "ачкам", bg: "чакам") unless Word.exists?(spindi: "ачкам")
Word.create(spindi: "разжитие", bg: "развитие") unless Word.exists?(spindi: "разжитие")
Word.create(spindi: "ду", bg: "до") unless Word.exists?(spindi: "ду")
Word.create(spindi: "дема", bg: "дена") unless Word.exists?(spindi: "дема")
Word.create(spindi: "спуделай", bg: "споделяй") unless Word.exists?(spindi: "спуделай")
Word.create(spindi: "знайат", bg: "знаят") unless Word.exists?(spindi: "знайат")
Word.create(spindi: "истимата", bg: "истината") unless Word.exists?(spindi: "истимата")
Word.create(spindi: "истима", bg: "истина") unless Word.exists?(spindi: "истима")
Word.create(spindi: "полодиахххххххххх", bg: "полудяхххххххххх") unless Word.exists?(spindi: "полодиахххххххххх")
Word.create(spindi: "споделаи", bg: "сподели") unless Word.exists?(spindi: "споделаи")
Word.create(spindi: "жиждаш", bg: "виждаш") unless Word.exists?(spindi: "жиждаш")
Word.create(spindi: "сажалиажам", bg: "съжалявам") unless Word.exists?(spindi: "сажалиажам")
Word.create(spindi: "убичам", bg: "обичам") unless Word.exists?(spindi: "убичам")
Word.create(spindi: "какау", bg: "какао") unless Word.exists?(spindi: "какау")
Word.create(spindi: "иттт", bg: "тиии") unless Word.exists?(spindi: "иттт")
Word.create(spindi: "коврооо", bg: "курвооо") unless Word.exists?(spindi: "коврооо")
Word.create(spindi: "мраснааа", bg: "мръснааа") unless Word.exists?(spindi: "мраснааа")
Word.create(spindi: "фокос", bg: "фокус") unless Word.exists?(spindi: "фокос")
Word.create(spindi: "мокос", bg: "мокус") unless Word.exists?(spindi: "мокос")
Word.create(spindi: "препаракос", bg: "препаратус") unless Word.exists?(spindi: "препаракос")
Word.create(spindi: "шладка", bg: "сладка") unless Word.exists?(spindi: "шладка")
Word.create(spindi: "преградка", bg: "прегръдка") unless Word.exists?(spindi: "преградка")
Word.create(spindi: "теп", bg: "теб") unless Word.exists?(spindi: "теп")
Word.create(spindi: "брам", bg: "бръм") unless Word.exists?(spindi: "брам")
Word.create(spindi: "миал", bg: "мяу") unless Word.exists?(spindi: "миал")
Word.create(spindi: "онишажам", bg: "унижавам") unless Word.exists?(spindi: "онишажам")
Word.create(spindi: "ковритеее", bg: "курвитеее") unless Word.exists?(spindi: "ковритеее")
Word.create(spindi: "частит", bg: "честит") unless Word.exists?(spindi: "частит")
Word.create(spindi: "сжети", bg: "свети") unless Word.exists?(spindi: "сжети")
Word.create(spindi: "жалемтим", bg: "валентин", name: true) unless Word.exists?(spindi: "жалемтим")
Word.create(spindi: "тапа", bg: "тъпа") unless Word.exists?(spindi: "тапа")
Word.create(spindi: "касам", bg: "късам") unless Word.exists?(spindi: "касам")
Word.create(spindi: "бошиата", bg: "божията") unless Word.exists?(spindi: "бошиата")
Word.create(spindi: "проштажа", bg: "прощава") unless Word.exists?(spindi: "проштажа")
Word.create(spindi: "кабрио", bg: "каприо", name: true) unless Word.exists?(spindi: "кабрио")
Word.create(spindi: "жиж", bg: "виж") unless Word.exists?(spindi: "жиж")
Word.create(spindi: "чок", bg: "чук") unless Word.exists?(spindi: "чок")
Word.create(spindi: "ема", bg: "има") unless Word.exists?(spindi: "ема")
Word.create(spindi: "ток", bg: "тук") unless Word.exists?(spindi: "ток")
Word.create(spindi: "найаде", bg: "наяде") unless Word.exists?(spindi: "найаде")
Word.create(spindi: "хой", bg: "хуй") unless Word.exists?(spindi: "хой")
Word.create(spindi: "кор", bg: "кур") unless Word.exists?(spindi: "кор")
Word.create(spindi: "знимах", bg: "снимах") unless Word.exists?(spindi: "знимах")
Word.create(spindi: "онижажам", bg: "унижавам") unless Word.exists?(spindi: "онижажам")
Word.create(spindi: "тамц", bg: "танц") unless Word.exists?(spindi: "тамц")
Word.create(spindi: "ес", bg: "се") unless Word.exists?(spindi: "ес")
Word.create(spindi: "тупка", bg: "топка") unless Word.exists?(spindi: "тупка")
Word.create(spindi: "ковро", bg: "курво") unless Word.exists?(spindi: "ковро")
Word.create(spindi: "отказжа", bg: "отказва") unless Word.exists?(spindi: "отказжа")
Word.create(spindi: "муга", bg: "мога") unless Word.exists?(spindi: "муга")
Word.create(spindi: "опрйа", bg: "оправя") unless Word.exists?(spindi: "опрйа")
Word.create(spindi: "претна", bg: "предна") unless Word.exists?(spindi: "претна")
Word.create(spindi: "претната", bg: "предната") unless Word.exists?(spindi: "претната")
Word.create(spindi: "гома", bg: "гума") unless Word.exists?(spindi: "гома")
Word.create(spindi: "кулата", bg: "колата") unless Word.exists?(spindi: "кулата")
Word.create(spindi: "изкам", bg: "искам") unless Word.exists?(spindi: "изкам")
Word.create(spindi: "дури", bg: "дори") unless Word.exists?(spindi: "дури")
Word.create(spindi: "зтарци", bg: "старци") unless Word.exists?(spindi: "зтарци")
Word.create(spindi: "зтарците", bg: "старците") unless Word.exists?(spindi: "зтарците")
Word.create(spindi: "кефиат", bg: "кефят") unless Word.exists?(spindi: "кефиат")
Word.create(spindi: "бостер", bg: "бустер") unless Word.exists?(spindi: "бостер")
Word.create(spindi: "бостера", bg: "бустера") unless Word.exists?(spindi: "бостера")
Word.create(spindi: "хжана", bg: "хвана") unless Word.exists?(spindi: "хжана")
Word.create(spindi: "преджи", bg: "пречи") unless Word.exists?(spindi: "преджи")
Word.create(spindi: "паршено", bg: "пържено") unless Word.exists?(spindi: "паршено")
Word.create(spindi: "клег", bg: "клек") unless Word.exists?(spindi: "клег")
Word.create(spindi: "речнига", bg: "речника") unless Word.exists?(spindi: "речнига")
Word.create(spindi: "доми", bg: "думи") unless Word.exists?(spindi: "доми")
