# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
# Word.create(spindi: 'макло', bg: 'малко')
# Word.create(spindi: 'ас', bg: 'аз')
# Word.create(spindi: 'фостата', bg: 'в устата')
# Word.create(spindi: 'биах', bg: 'бях')
# Word.create(spindi: 'ф', bg: 'в')
# Word.create(spindi: 'луксозенец', bg: 'лозенец')

Word.create(spindi: "жиги", bg: "фики", name: true)
Word.create(spindi: "биа", bg: "бия")
Word.create(spindi: "поскан", bg: "пускам")
Word.create(spindi: "салза", bg: "сълза")
Word.create(spindi: "проатели", bg: "приятели")
Word.create(spindi: "дема", bg: "дена")
Word.create(spindi: "нажършфат", bg: "навършват")
Word.create(spindi: "годими", bg: "години")
Word.create(spindi: "уткакто", bg: "откакто")
Word.create(spindi: "затжорха", bg: "затвориха")
Word.create(spindi: "пържата", bg: "първата")
Word.create(spindi: "страмица", bg: "страница")
Word.create(spindi: "точмо", bg: "точно")
Word.create(spindi: "ан", bg: "на")
Word.create(spindi: "хелороин", bg: "хелуин", name: true)
Word.create(spindi: "бади", bg: "бъде")
Word.create(spindi: "смарт", bg: "смърт")
Word.create(spindi: "мрасна", bg: "мръсна")
Word.create(spindi: "фесбок", bg: "фейсбук")
Word.create(spindi: "са", bg: "се")
Word.create(spindi: "сас", bg: "със")
Word.create(spindi: "бес", bg: "без")
Word.create(spindi: "жас", bg: "вас")
Word.create(spindi: "ниамаше", bg: "нямаше")
Word.create(spindi: "ад", bg: "да")
Word.create(spindi: "сам", bg: "съм")
Word.create(spindi: "такаж", bg: "такъв")
Word.create(spindi: "тапаг", bg: "тъпак")
Word.create(spindi: "макиа", bg: "майка")
Word.create(spindi: "мо", bg: "му")
Word.create(spindi: "дайба", bg: "даеба")
Word.create(spindi: "еш", bg: "ще")
Word.create(spindi: "ема", bg: "има")
Word.create(spindi: "дзан", bg: "дзън")
Word.create(spindi: "жоржану", bg: "джорджано", name: true)
Word.create(spindi: "комтрол", bg: "контрол")
Word.create(spindi: "атемтат", bg: "атентат")
Word.create(spindi: "жаж", bg: "във")
Word.create(spindi: "еслианска", bg: "ислямска")
Word.create(spindi: "даржажа", bg: "държава")
Word.create(spindi: "евакоирват", bg: "евакуират")
Word.create(spindi: "хрестианите", bg: "християните")
Word.create(spindi: "хрестиани", bg: "християни")
Word.create(spindi: "костажа", bg: "ко става")
Word.create(spindi: "тажем", bg: "тъжен")
Word.create(spindi: "сан", bg: "съм")
Word.create(spindi: "зими", bg: "вземи")
Word.create(spindi: "тос", bg: "този")
Word.create(spindi: "соджок", bg: "суджук")
Word.create(spindi: "оспокоиш", bg: "успокоиш")
Word.create(spindi: "100", bg: "защо")
Word.create(spindi: "тей", bg: "така")
Word.create(spindi: "праес", bg: "правиш")
Word.create(spindi: "накаши", bg: "накаже")
Word.create(spindi: "аз", bg: "за")
Word.create(spindi: "кидето", bg: "където")
Word.create(spindi: "сжинско", bg: "свинско")
Word.create(spindi: "ж", bg: "в")
Word.create(spindi: "соджока", bg: "суджука")
Word.create(spindi: "лодокорци", bg: "лудогорци")
Word.create(spindi: "консержирани", bg: "консервирани")
Word.create(spindi: "мангости", bg: "мангусти")
Word.create(spindi: "чичу", bg: "чичо")
Word.create(spindi: "харесжа", bg: "харесва")
Word.create(spindi: "тожа", bg: "това")
Word.create(spindi: "дейба", bg: "даеба")
Word.create(spindi: "оспиах", bg: "успях")
Word.create(spindi: "ниакои", bg: "някой")
Word.create(spindi: "продажа", bg: "продава")
Word.create(spindi: "хубаж", bg: "хубав")
Word.create(spindi: "гранутомет", bg: "гранатомет")
Word.create(spindi: "едим", bg: "един")
Word.create(spindi: "проател", bg: "приятел")
Word.create(spindi: "петам", bg: "питам")
Word.create(spindi: "саради", bg: "заради")
Word.create(spindi: "ковра", bg: "курва")
Word.create(spindi: "стажай", bg: "ставай")
Word.create(spindi: "иа", bg: "я")
Word.create(spindi: "зтига", bg: "стига")
Word.create(spindi: "з", bg: "с")
Word.create(spindi: "тиа", bg: "тия")
Word.create(spindi: "коври", bg: "курви")
Word.create(spindi: "утивай", bg: "отивай")
Word.create(spindi: "трениргаш", bg: "тренираш")
Word.create(spindi: "диадо", bg: "дядо")
Word.create(spindi: "дзенен", bg: "ценен")
Word.create(spindi: "савед", bg: "съвет")
Word.create(spindi: "полочих", bg: "получих")
Word.create(spindi: "ут", bg: "от")
Word.create(spindi: "жлиса", bg: "влиза")
Word.create(spindi: "селианин", bg: "селянин")
Word.create(spindi: "крачма", bg: "кръчма")
Word.create(spindi: "казжа", bg: "казва")
Word.create(spindi: "пийниаците", bg: "пияниците")
Word.create(spindi: "жатре", bg: "вътре")
Word.create(spindi: "онриал", bg: "умрял")
Word.create(spindi: "маикал", bg: "майкъл", name: true)
Word.create(spindi: "джексам", bg: "джексън", name: true)
Word.create(spindi: "шокирван", bg: "шокиран")
Word.create(spindi: "дрог", bg: "друг")
Word.create(spindi: "ждигнал", bg: "вдигнал")
Word.create(spindi: "рака", bg: "ръка")
Word.create(spindi: "трепереш", bg: "треперещ")
Word.create(spindi: "дубре", bg: "добре")
Word.create(spindi: "ил", bg: "ли")
Word.create(spindi: "деск", bg: "диск")
Word.create(spindi: "сано", bg: "само")
Word.create(spindi: "зрабско", bg: "сръбско")
Word.create(spindi: "ен", bg: "не")
Word.create(spindi: "поуодиажан", bg: "полудявам")
Word.create(spindi: "губи", bg: "гуфи", name: true)
Word.create(spindi: "педрас", bg: "педераст")
Word.create(spindi: "типичем", bg: "типичен")
Word.create(spindi: "жъпрос", bg: "въпрос")
Word.create(spindi: "хурата", bg: "хората")
Word.create(spindi: "арема", bg: "арена")
Word.create(spindi: "армец", bg: "армеец")
Word.create(spindi: "сига", bg: "сега")
Word.create(spindi: "комцерта", bg: "концерта")
Word.create(spindi: "комцерт", bg: "концерт")
Word.create(spindi: "пламета", bg: "планета")
Word.create(spindi: "ебасимо", bg: "еби му")
Word.create(spindi: "сешташ", bg: "сещаш")
Word.create(spindi: "нале", bg: "нали")
Word.create(spindi: "емаш", bg: "имаш")
Word.create(spindi: "едми", bg: "едни")
Word.create(spindi: "крага", bg: "крака")
Word.create(spindi: "куго", bg: "кого")
Word.create(spindi: "питан", bg: "питам")
Word.create(spindi: "праиш", bg: "правиш")
Word.create(spindi: "кот", bg: "каквото")
Word.create(spindi: "такоа", bg: "такова")
Word.create(spindi: "поздраж", bg: "поздрав")
Word.create(spindi: "боклици", bg: "боклуци")
Word.create(spindi: "боклик", bg: "боклук")
Word.create(spindi: "ште", bg: "ще")
Word.create(spindi: "расбиа", bg: "разбия")
Word.create(spindi: "глажата", bg: "главата")
Word.create(spindi: "глажа", bg: "глава")
Word.create(spindi: "малак", bg: "малък")
Word.create(spindi: "зо", bg: "за")
Word.create(spindi: "двайси", bg: "двайсет")
Word.create(spindi: "пед", bg: "пет")
Word.create(spindi: "пожече", bg: "повече")
Word.create(spindi: "жамии", bg: "джамии")
Word.create(spindi: "откоклото", bg: "отколкото")
Word.create(spindi: "петстин", bg: "петстотин")
Word.create(spindi: "торско", bg: "турско")
Word.create(spindi: "ропство", bg: "робство")
Word.create(spindi: "добар", bg: "добър")
Word.create(spindi: "десем", bg: "десен")
Word.create(spindi: "глопаци", bg: "глупаци")
Word.create(spindi: "дрогариа", bg: "другаря")
Word.create(spindi: "жолен", bg: "волен")
Word.create(spindi: "одари", bg: "удари")
Word.create(spindi: "болем", bg: "волен", name: true)
Word.create(spindi: "снам", bg: "знам")
Word.create(spindi: "беши", bg: "беше")
Word.create(spindi: "ассам", bg: "аз съм")
Word.create(spindi: "бок", bg: "бог")
Word.create(spindi: "чи", bg: "че")
Word.create(spindi: "ша", bg: "ще")
Word.create(spindi: "кръф", bg: "кръв")
Word.create(spindi: "еи", bg: "ей")
Word.create(spindi: "сиа", bg: "сега")
Word.create(spindi: "ит", bg: "ти")
Word.create(spindi: "ибах", bg: "ебах")
Word.create(spindi: "подката", bg: "путката")
Word.create(spindi: "подка", bg: "путка")
Word.create(spindi: "маена", bg: "майна")
Word.create(spindi: "болеме", bg: "волене", name: true)
Word.create(spindi: "кои", bg: "кой")
Word.create(spindi: "ма", bg: "ме")
Word.create(spindi: "жереми", bg: "джеръми", name: true)
Word.create(spindi: "порнуто", bg: "порното")
Word.create(spindi: "гласожал", bg: "гласувал")
Word.create(spindi: "хаскожо", bg: "хасково", name: true)
Word.create(spindi: "естемски", bg: "истински")
Word.create(spindi: "паг", bg: "пак")
Word.create(spindi: "надросал", bg: "надрусал")
Word.create(spindi: "едмо", bg: "едно")
Word.create(spindi: "йасно", bg: "ясно")
Word.create(spindi: "намера", bg: "намира")
Word.create(spindi: "блиско", bg: "близко")
Word.create(spindi: "фцентара", bg: "в центъра")
Word.create(spindi: "гласужа", bg: "гласува")
Word.create(spindi: "ена", bg: "една")
Word.create(spindi: "омна", bg: "умна")
Word.create(spindi: "мисал", bg: "мисъл")
Word.create(spindi: "гласожах", bg: "гласувах")
Word.create(spindi: "праите", bg: "правите")
Word.create(spindi: "маи", bg: "май")
Word.create(spindi: "подлодиало", bg: "полудяло")
Word.create(spindi: "амфетмо", bg: "амфетно")
Word.create(spindi: "джодже", bg: "джудже")
Word.create(spindi: "дажайте", bg: "давайте")
Word.create(spindi: "фиргаме", bg: "хвърляме")
Word.create(spindi: "ибем", bg: "ебем")
Word.create(spindi: "за100то", bg: "защото")
Word.create(spindi: "недожолен", bg: "недоволен")
Word.create(spindi: "лошу", bg: "лошо")
Word.create(spindi: "гласожа", bg: "гласува")
Word.create(spindi: "есбореите", bg: "изборите")
Word.create(spindi: "накротици", bg: "наркотици")
Word.create(spindi: "подлодиажане", bg: "полудяване")
Word.create(spindi: "подлодиал", bg: "полудял")
Word.create(spindi: "фарлиам", bg: "хвърлям")
Word.create(spindi: "бонби", bg: "бомби")
Word.create(spindi: "полециата", bg: "полицията")
Word.create(spindi: "пордажан", bg: "продавам")
Word.create(spindi: "комтрабанда", bg: "контрабанда")
Word.create(spindi: "пеежски", bg: "пеевски", name: true)
Word.create(spindi: "бартмо", bg: "брат му")
Word.create(spindi: "лодокорски", bg: "лудогорски")
Word.create(spindi: "кренжирш", bg: "кренвирш")
Word.create(spindi: "кренжирши", bg: "кренвирши")
Word.create(spindi: "конентар", bg: "коментар")
Word.create(spindi: "кадшаг", bg: "качак")
Word.create(spindi: "зпри", bg: "спри")
Word.create(spindi: "нарготиците", bg: "наркотиците")
Word.create(spindi: "тапото", bg: "тъпото")
Word.create(spindi: "реглама", bg: "реклама")
Word.create(spindi: "платема", bg: "платена")
Word.create(spindi: "зелеми", bg: "зелени")
Word.create(spindi: "гоштери", bg: "гущери")
Word.create(spindi: "полодиажам", bg: "полудявам")
Word.create(spindi: "петаг", bg: "петък")
Word.create(spindi: "слагаи", bg: "слагай")
Word.create(spindi: "рикиа", bg: "ракия")
Word.create(spindi: "рикиата", bg: "ракията")
Word.create(spindi: "салада", bg: "салата")
Word.create(spindi: "саладата", bg: "салатата")
Word.create(spindi: "таси", bg: "тази")
Word.create(spindi: "ескан", bg: "искам")
Word.create(spindi: "миозик", bg: "мюзик")
Word.create(spindi: "пажликени", bg: "павликени", name: true)
Word.create(spindi: "гласожайти", bg: "гласувайте")
Word.create(spindi: "божестжено", bg: "божествено")
Word.create(spindi: "докосжане", bg: "докосване")
Word.create(spindi: "пумогна", bg: "помогна")
Word.create(spindi: "лижърпол", bg: "ливърпуул", name: true)
Word.create(spindi: "молиа", bg: "моля")
Word.create(spindi: "очебниг", bg: "учебник")
Word.create(spindi: "ракеда", bg: "ракета")
Word.create(spindi: "од", bg: "от")
Word.create(spindi: "еграи", bg: "играе")
Word.create(spindi: "братожчеда", bg: "братовчеда")
Word.create(spindi: "еграча", bg: "играча")
Word.create(spindi: "еграч", bg: "играч")
Word.create(spindi: "перниг", bg: "перник", name: true)
Word.create(spindi: "коврите", bg: "курвите")
Word.create(spindi: "калват", bg: "кълват")
Word.create(spindi: "голв", bg: "голф")
Word.create(spindi: "софеа", bg: "софия", name: true)
Word.create(spindi: "адибас", bg: "адидас")
Word.create(spindi: "боргас", bg: "бургас", name: true)
Word.create(spindi: "анцумг", bg: "анцуг")
Word.create(spindi: "анцумга", bg: "анцуга")
Word.create(spindi: "жижот", bg: "живот")
Word.create(spindi: "лиобоф", bg: "любов")
Word.create(spindi: "лиобофта", bg: "любовта")
Word.create(spindi: "ниама", bg: "няма")
Word.create(spindi: "гранитси", bg: "граници")
Word.create(spindi: "ибането", bg: "ебането")
Word.create(spindi: "торски", bg: "турски")
Word.create(spindi: "росалка", bg: "русалка")
Word.create(spindi: "росалки", bg: "русалки")
Word.create(spindi: "билгариа", bg: "българия", name: true)
Word.create(spindi: "скору", bg: "скоро")
Word.create(spindi: "вав", bg: "във")
Word.create(spindi: "еслиама", bg: "исляма")
Word.create(spindi: "религиа", bg: "религия")
Word.create(spindi: "киото", bg: "който")
Word.create(spindi: "тварди", bg: "твърди")
Word.create(spindi: "обрадното", bg: "обратното")
Word.create(spindi: "обием", bg: "убием")
Word.create(spindi: "ромалдо", bg: "роналдо", name: true)
Word.create(spindi: "педраза", bg: "педераста")
Word.create(spindi: "набарзо", bg: "набързо")
Word.create(spindi: "избиага", bg: "избяга")
Word.create(spindi: "расизан", bg: "расизъм")
Word.create(spindi: "к", bg: "ок")
Word.create(spindi: "лиобимиа", bg: "любимия")
Word.create(spindi: "продалжение", bg: "продължение")
Word.create(spindi: "виш", bg: "виж")
Word.create(spindi: "вътле", bg: "вътре")
Word.create(spindi: "бротален", bg: "брутален")
Word.create(spindi: "маека", bg: "майка")
Word.create(spindi: "потката", bg: "путката")
Word.create(spindi: "довре", bg: "добре")
Word.create(spindi: "торциа", bg: "турция", name: true)
Word.create(spindi: "за100", bg: "защо")
Word.create(spindi: "штот", bg: "защото")
Word.create(spindi: "дъа", bg: "дееба")
